// <auto-generated />
namespace IMS2.ImsDbContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DecimalTo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DecimalTo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201605220159351_DecimalTo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
