//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FromExcelResourceFile {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FromExcelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FromExcelResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FromExcelResourceFile.FromExcelResource", typeof(FromExcelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 麻醉相关死亡人数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData1 {
            get {
                return ResourceManager.GetString("AnesthesiologyData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 椎管内麻醉神经并发症截瘫发生例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData10 {
            get {
                return ResourceManager.GetString("AnesthesiologyData10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬膜外阻滞成功例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData2 {
            get {
                return ResourceManager.GetString("AnesthesiologyData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬膜外阻滞总例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData3 {
            get {
                return ResourceManager.GetString("AnesthesiologyData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神经阻滞麻醉成功例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData4 {
            get {
                return ResourceManager.GetString("AnesthesiologyData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神经阻滞麻醉总例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData5 {
            get {
                return ResourceManager.GetString("AnesthesiologyData5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬膜外麻醉硬脊膜穿破发生例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData6 {
            get {
                return ResourceManager.GetString("AnesthesiologyData6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬膜外麻醉总例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData7 {
            get {
                return ResourceManager.GetString("AnesthesiologyData7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 椎管内麻醉神经并发症发生例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData8 {
            get {
                return ResourceManager.GetString("AnesthesiologyData8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 椎管内麻醉总例数 的本地化字符串。
        /// </summary>
        public static string AnesthesiologyData9 {
            get {
                return ResourceManager.GetString("AnesthesiologyData9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预约诊疗总人次 的本地化字符串。
        /// </summary>
        public static string ClinicData1 {
            get {
                return ResourceManager.GetString("ClinicData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预约号源数 的本地化字符串。
        /// </summary>
        public static string ClinicData2 {
            get {
                return ResourceManager.GetString("ClinicData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POCT项目对比例数 的本地化字符串。
        /// </summary>
        public static string ExamineData1 {
            get {
                return ResourceManager.GetString("ExamineData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POCT项目总数 的本地化字符串。
        /// </summary>
        public static string ExamineData2 {
            get {
                return ResourceManager.GetString("ExamineData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危急值报告及时例数 的本地化字符串。
        /// </summary>
        public static string ExamineData3 {
            get {
                return ResourceManager.GetString("ExamineData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危急值总例数 的本地化字符串。
        /// </summary>
        public static string ExamineData4 {
            get {
                return ResourceManager.GetString("ExamineData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药品总费用 的本地化字符串。
        /// </summary>
        public static string FinanceData1 {
            get {
                return ResourceManager.GetString("FinanceData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总费用 的本地化字符串。
        /// </summary>
        public static string FinanceData2 {
            get {
                return ResourceManager.GetString("FinanceData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专科及门急诊总费用 的本地化字符串。
        /// </summary>
        public static string FinanceData3 {
            get {
                return ResourceManager.GetString("FinanceData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专科及门急诊药品费用 的本地化字符串。
        /// </summary>
        public static string FinanceData4 {
            get {
                return ResourceManager.GetString("FinanceData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [YG-1-1]医院感染新发人数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData1 {
            get {
                return ResourceManager.GetString("InfectionManagementData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正确的洗手人数【抽查】 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData10 {
            get {
                return ResourceManager.GetString("InfectionManagementData10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 洗手总人数【抽查】 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData11 {
            get {
                return ResourceManager.GetString("InfectionManagementData11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际实施手卫生次数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData12 {
            get {
                return ResourceManager.GetString("InfectionManagementData12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应实施手卫生次数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData13 {
            get {
                return ResourceManager.GetString("InfectionManagementData13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手术部位感染上报例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData14 {
            get {
                return ResourceManager.GetString("InfectionManagementData14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [YG-11-1]I类切口手术部位感染例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData15 {
            get {
                return ResourceManager.GetString("InfectionManagementData15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血管内导管相关血流感染发病例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData16 {
            get {
                return ResourceManager.GetString("InfectionManagementData16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血管内导管留置总天数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData17 {
            get {
                return ResourceManager.GetString("InfectionManagementData17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼吸机相关肺炎发病例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData18 {
            get {
                return ResourceManager.GetString("InfectionManagementData18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼吸机使用总天数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData19 {
            get {
                return ResourceManager.GetString("InfectionManagementData19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [YG-3-1]医院感染总例次 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData2 {
            get {
                return ResourceManager.GetString("InfectionManagementData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导尿管相关泌尿系感染发病例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData20 {
            get {
                return ResourceManager.GetString("InfectionManagementData20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导尿管使用总天数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData21 {
            get {
                return ResourceManager.GetString("InfectionManagementData21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医院感染现患人数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData22 {
            get {
                return ResourceManager.GetString("InfectionManagementData22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医院感染现患检测时间住院人数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData23 {
            get {
                return ResourceManager.GetString("InfectionManagementData23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [YG-4-1]医院感染漏报例次 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData3 {
            get {
                return ResourceManager.GetString("InfectionManagementData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用非限制级抗菌药物前病原学送检例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData4 {
            get {
                return ResourceManager.GetString("InfectionManagementData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用非限制级抗菌药物总例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData5 {
            get {
                return ResourceManager.GetString("InfectionManagementData5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用限制级抗菌药物前病原学送检例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData6 {
            get {
                return ResourceManager.GetString("InfectionManagementData6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用限制级抗菌药物总例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData7 {
            get {
                return ResourceManager.GetString("InfectionManagementData7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用特殊级抗菌药物前病原学送检例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData8 {
            get {
                return ResourceManager.GetString("InfectionManagementData8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用特殊级抗菌药物总例数 的本地化字符串。
        /// </summary>
        public static string InfectionManagementData9 {
            get {
                return ResourceManager.GetString("InfectionManagementData9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总卫生材料收入 的本地化字符串。
        /// </summary>
        public static string MaterialsStatisticalData1 {
            get {
                return ResourceManager.GetString("MaterialsStatisticalData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【物资】总收入 的本地化字符串。
        /// </summary>
        public static string MaterialsStatisticalData2 {
            get {
                return ResourceManager.GetString("MaterialsStatisticalData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卫材总领用 的本地化字符串。
        /// </summary>
        public static string MaterialsStatisticalData3 {
            get {
                return ResourceManager.GetString("MaterialsStatisticalData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【物资】不含药品收入 的本地化字符串。
        /// </summary>
        public static string MaterialsStatisticalData4 {
            get {
                return ResourceManager.GetString("MaterialsStatisticalData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病历回收数 的本地化字符串。
        /// </summary>
        public static string MedicalRecordStatisticalData1 {
            get {
                return ResourceManager.GetString("MedicalRecordStatisticalData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手术冰冻与石蜡诊断符合例数 的本地化字符串。
        /// </summary>
        public static string MedicalRecordStatisticalData2 {
            get {
                return ResourceManager.GetString("MedicalRecordStatisticalData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手术冰冻与石蜡诊报告总例数 的本地化字符串。
        /// </summary>
        public static string MedicalRecordStatisticalData3 {
            get {
                return ResourceManager.GetString("MedicalRecordStatisticalData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规诊断报告准确例数【抽查】 的本地化字符串。
        /// </summary>
        public static string PathologyData1 {
            get {
                return ResourceManager.GetString("PathologyData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规诊断报告总例数【抽查】 的本地化字符串。
        /// </summary>
        public static string PathologyData2 {
            get {
                return ResourceManager.GetString("PathologyData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病理诊断报告在5个工作日内发出例数 的本地化字符串。
        /// </summary>
        public static string PathologyData3 {
            get {
                return ResourceManager.GetString("PathologyData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病理诊断报告总例数 的本地化字符串。
        /// </summary>
        public static string PathologyData4 {
            get {
                return ResourceManager.GetString("PathologyData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病理报告书内容与格式书写合格例数【抽查】 的本地化字符串。
        /// </summary>
        public static string PathologyData5 {
            get {
                return ResourceManager.GetString("PathologyData5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病理报告总例数【抽查】 的本地化字符串。
        /// </summary>
        public static string PathologyData6 {
            get {
                return ResourceManager.GetString("PathologyData6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住院病人抗菌药物使用人数 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData1 {
            get {
                return ResourceManager.GetString("PharmaceuticalData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗菌药物消耗量 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData2 {
            get {
                return ResourceManager.GetString("PharmaceuticalData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基药总费用 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData3 {
            get {
                return ResourceManager.GetString("PharmaceuticalData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药品总费用【基药】 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData4 {
            get {
                return ResourceManager.GetString("PharmaceuticalData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I类切口手术抗菌药物预防使用例数 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData5 {
            get {
                return ResourceManager.GetString("PharmaceuticalData5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 除外治疗性用药的Ⅰ类切口手术例数 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData6 {
            get {
                return ResourceManager.GetString("PharmaceuticalData6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门诊使用抗菌药物人数 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData7 {
            get {
                return ResourceManager.GetString("PharmaceuticalData7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 急诊使用抗菌药物人数 的本地化字符串。
        /// </summary>
        public static string PharmaceuticalData8 {
            get {
                return ResourceManager.GetString("PharmaceuticalData8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医学影像诊断与手术后符合例数【放射】【抽查】 的本地化字符串。
        /// </summary>
        public static string RadiologyData1 {
            get {
                return ResourceManager.GetString("RadiologyData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医学影像诊断例数【放射】【抽查】 的本地化字符串。
        /// </summary>
        public static string RadiologyData2 {
            get {
                return ResourceManager.GetString("RadiologyData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 康复治疗有效患者数 的本地化字符串。
        /// </summary>
        public static string RehabilitationData1 {
            get {
                return ResourceManager.GetString("RehabilitationData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 康复治疗患者数 的本地化字符串。
        /// </summary>
        public static string RehabilitationData2 {
            get {
                return ResourceManager.GetString("RehabilitationData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住院患者康复功能评定例数 的本地化字符串。
        /// </summary>
        public static string RehabilitationData3 {
            get {
                return ResourceManager.GetString("RehabilitationData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完好设备数 的本地化字符串。
        /// </summary>
        public static string RehabilitationData4 {
            get {
                return ResourceManager.GetString("RehabilitationData4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备总数 的本地化字符串。
        /// </summary>
        public static string RehabilitationData5 {
            get {
                return ResourceManager.GetString("RehabilitationData5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医学影像诊断与手术后符合例数【超声】【抽查】 的本地化字符串。
        /// </summary>
        public static string UltrasoundData1 {
            get {
                return ResourceManager.GetString("UltrasoundData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医学影像诊断例数【超声】【抽查】 的本地化字符串。
        /// </summary>
        public static string UltrasoundData2 {
            get {
                return ResourceManager.GetString("UltrasoundData2", resourceCulture);
            }
        }
    }
}
